services:
  - type: web
    name: buono-tax-invoice
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: buono-db
          property: connectionString
      - key: GIN_MODE
        value: release

databases:
  - name: buono-db
    plan: free
    databaseName: buono_tax_invoice
    user: buono_admin
